project:
  type: website
  render:

    - index.qmd

    - content/le_docteur/index.qmd
    - content/le_docteur/consultations.qmd
    - content/le_docteur/biographie.qmd
    - content/le_docteur/cv.qmd

    - content/livres_fr/index.qmd
    - content/livres_fr/3_approches_du_soin_psychique.qmd
    - content/livres_fr/apprendre_a_gerer_son_stress.qmd
    - content/livres_fr/au_dela_des_mots.qmd
    - content/livres_fr/cannabis_du_plaisir_au_risque.qmd
    - content/livres_fr/cas_cliniques_en_tcc_1.qmd
    - content/livres_fr/cas_cliniques_en_tcc_2.qmd
    - content/livres_fr/cas_cliniques_en_tcc_3.qmd
    - content/livres_fr/chambre_isolement_contention.qmd
    - content/livres_fr/coachez_votre_vie.qmd
    - content/livres_fr/communication_observance_psy.qmd
    - content/livres_fr/controle_et_gestion_du_stress.qmd
    - content/livres_fr/depression_et_anxiete.qmd
    - content/livres_fr/dire_pour_vivre.qmd
    - content/livres_fr/dynamique_equipe_soignante.qmd
    - content/livres_fr/ecarts_de_conduite.qmd
    - content/livres_fr/en_finir_avec_l_insomnie.qmd
    - content/livres_fr/epreuve_maladie_organique.qmd
    - content/livres_fr/gerer_les_conflits.qmd
    - content/livres_fr/gestion_stress_aquaphobie_tcc.qmd
    - content/livres_fr/guerir_vite.qmd
    - content/livres_fr/guide_urgence_psychiatrique.qmd
    - content/livres_fr/homosexualite_en_afrique.qmd
    - content/livres_fr/information_du_patient.qmd
    - content/livres_fr/informer_patient_en_psychiatrie.qmd
    - content/livres_fr/institution_psychiatrique.qmd
    - content/livres_fr/isolement_contention_contrainte.qmd
    - content/livres_fr/je_me_libere_de_mes_phobies.qmd
    - content/livres_fr/je_triomphe_de_l_insomnie.qmd
    - content/livres_fr/la_psychologie_positive.qmd
    - content/livres_fr/le_cannabis_en_question.qmd
    - content/livres_fr/les_essentiels_des_tcc.qmd
    - content/livres_fr/les_exclus_de_la_cite.qmd
    - content/livres_fr/les_psychoses.qmd
    - content/livres_fr/les_tcc_1.qmd
    - content/livres_fr/les_tcc_2.qmd
    - content/livres_fr/les_tcc_du_sujet_age.qmd
    - content/livres_fr/les_tcc_manuel_pratique.qmd
    - content/livres_fr/les_therapies_breves.qmd
    - content/livres_fr/les_troubles_de_la_personnalite.qmd
    - content/livres_fr/ma_bible_des_tcc.qmd
    - content/livres_fr/mots_corps_maux_ame.qmd
    - content/livres_fr/observance_medicamenteuse.qmd
    - content/livres_fr/petit_precis_psychologie_positive.qmd
    - content/livres_fr/petite_histoire_masturbation.qmd
    - content/livres_fr/psychotherapies_du_sujet_age.qmd
    - content/livres_fr/reflexions_vieillissement.qmd
    - content/livres_fr/risques_et_plongee.qmd
    - content/livres_fr/sante_mentale_neurologique.qmd
    - content/livres_fr/schizophrenie_diagnostic.qmd
    - content/livres_fr/se_soigner_par_les_tcc.qmd
    - content/livres_fr/sida_et_seropositivite.qmd
    - content/livres_fr/sortir_toxicomanie_addictions.qmd
    - content/livres_fr/stop_a_l_anxiete_sans_medoc.qmd
    - content/livres_fr/stop_a_l_anxiete.qmd
    - content/livres_fr/sur_le_fil_du_rasoir.qmd
    - content/livres_fr/surmonter_l_alcoolisme.qmd
    - content/livres_fr/surmonter_la_depression_1.qmd
    - content/livres_fr/surmonter_la_depression_2.qmd
    - content/livres_fr/tabagisme_plaisir_dependance.qmd
    - content/livres_fr/vaincre_l_anxiete_sans_medoc.qmd
    - content/livres_fr/vieillissement_bipolaire_schizo.qmd

    - content/books_other/index.qmd
    - content/books_other/defeat_insomnia.qmd
    - content/books_other/invinga_dependenta_de_alcool.qmd
    - content/books_other/nespavost_zbavte_se_ji_navzdy.qmd
    - content/books_other/sleep_better.qmd
    - content/books_other/strategies_fast_recovery.qmd
    - content/books_other/words_of_pain.qmd
    - content/books_other/لا للقلق.qmd

    - content/publications_communications/index.qmd
    - content/publications_communications/chapitres_ouvrages.qmd
    - content/publications_communications/articles_revues_indexees.qmd
    - content/publications_communications/articles_revues_non_indexees_avec_comite.qmd
    - content/publications_communications/articles_revues_non_indexees_sans_comite.qmd
    - content/publications_communications/communications_congres_internationaux.qmd
    - content/publications_communications/communications_congres_nationaux.qmd
    - content/publications_communications/posters_congres.qmd
    - content/publications_communications/interviews.qmd

    - content/autres_activites/index.qmd
    - content/autres_activites/encadrement_recherche.qmd
    - content/autres_activites/autre.qmd

website:
  title: "Dr Jérôme Palazzolo"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: "white"
    search: true
    left:
      - file: index.qmd
        text: Home
      - sidebar:le_docteur
      - text: Interviews
        href: https://www.facebook.com/media/set/?set=a.10150356662827691&type=3
      # - sidebar:livres_fr
      - file: content/livres_fr/index.qmd
        text: Livres (fr)
      # - sidebar:books_other
      - file: content/books_other/index.qmd
        text: Books (other)
      - sidebar:publications_communications
      - sidebar:autres_activites
    tools:
      - icon: github
        menu:
          - text: Code source
            url:  https://github.com/antoine-palazz/site-dr-palazzolo
  comments:
    giscus:
      repo: antoine-palazz/site-dr-palazzolo
  twitter-card: true
  site-url: https://docteurjeromepalazzolo.fr  # A modifier ?
  repo-url: https://github.com/antoine-palazz/site-dr-palazzolo
  repo-branch: main
  issue-url: https://github.com/antoine-palazz/site-dr-palazzolo/issues/new
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Site du Dr Jérôme Palazzolo<br>
      Licence MIT<br>
      Code source disponible sur [`Github`](https://github.com/antoine-palazz/site-dr-palazzolo)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      Par [Antoine Palazzolo](https://www.linkedin.com/in/antoine-palazzolo/)<br>
      Inspiration pour la mise en forme du site [ici](https://pythonds.linogaliana.fr/)<br>

  sidebar: 

    - id: home
      title: "Home"
      href: index.qmd
    
    - id: le_docteur
      title: "Le docteur"
      #collapse-level: 2
      contents:
        - content/le_docteur/index.qmd
        - content/le_docteur/consultations.qmd
        - content/le_docteur/biographie.qmd
        - content/le_docteur/cv.qmd

    - id: livres_fr
      title: "Livres (fr)"
      #collapse-level: 2
      contents:
        - content/livres_fr/index.qmd
        - content/livres_fr/3_approches_du_soin_psychique.qmd
        - content/livres_fr/apprendre_a_gerer_son_stress.qmd
        - content/livres_fr/au_dela_des_mots.qmd
        - content/livres_fr/cannabis_du_plaisir_au_risque.qmd
        - content/livres_fr/cas_cliniques_en_tcc_1.qmd
        - content/livres_fr/cas_cliniques_en_tcc_2.qmd
        - content/livres_fr/cas_cliniques_en_tcc_3.qmd
        - content/livres_fr/chambre_isolement_contention.qmd
        - content/livres_fr/coachez_votre_vie.qmd
        - content/livres_fr/communication_observance_psy.qmd
        - content/livres_fr/controle_et_gestion_du_stress.qmd
        - content/livres_fr/depression_et_anxiete.qmd
        - content/livres_fr/dire_pour_vivre.qmd
        - content/livres_fr/dynamique_equipe_soignante.qmd
        - content/livres_fr/ecarts_de_conduite.qmd
        - content/livres_fr/en_finir_avec_l_insomnie.qmd
        - content/livres_fr/epreuve_maladie_organique.qmd
        - content/livres_fr/gerer_les_conflits.qmd
        - content/livres_fr/gestion_stress_aquaphobie_tcc.qmd
        - content/livres_fr/guerir_vite.qmd
        - content/livres_fr/guide_urgence_psychiatrique.qmd
        - content/livres_fr/homosexualite_en_afrique.qmd
        - content/livres_fr/information_du_patient.qmd
        - content/livres_fr/informer_patient_en_psychiatrie.qmd
        - content/livres_fr/institution_psychiatrique.qmd
        - content/livres_fr/isolement_contention_contrainte.qmd
        - content/livres_fr/je_me_libere_de_mes_phobies.qmd
        - content/livres_fr/je_triomphe_de_l_insomnie.qmd
        - content/livres_fr/la_psychologie_positive.qmd
        - content/livres_fr/le_cannabis_en_question.qmd
        - content/livres_fr/les_essentiels_des_tcc.qmd
        - content/livres_fr/les_exclus_de_la_cite.qmd
        - content/livres_fr/les_psychoses.qmd
        - content/livres_fr/les_tcc_1.qmd
        - content/livres_fr/les_tcc_2.qmd
        - content/livres_fr/les_tcc_du_sujet_age.qmd
        - content/livres_fr/les_tcc_manuel_pratique.qmd
        - content/livres_fr/les_therapies_breves.qmd
        - content/livres_fr/les_troubles_de_la_personnalite.qmd
        - content/livres_fr/ma_bible_des_tcc.qmd
        - content/livres_fr/mots_corps_maux_ame.qmd
        - content/livres_fr/observance_medicamenteuse.qmd
        - content/livres_fr/petit_precis_psychologie_positive.qmd
        - content/livres_fr/petite_histoire_masturbation.qmd
        - content/livres_fr/psychotherapies_du_sujet_age.qmd
        - content/livres_fr/reflexions_vieillissement.qmd
        - content/livres_fr/risques_et_plongee.qmd
        - content/livres_fr/sante_mentale_neurologique.qmd
        - content/livres_fr/schizophrenie_diagnostic.qmd
        - content/livres_fr/se_soigner_par_les_tcc.qmd
        - content/livres_fr/sida_et_seropositivite.qmd
        - content/livres_fr/sortir_toxicomanie_addictions.qmd
        - content/livres_fr/stop_a_l_anxiete_sans_medoc.qmd
        - content/livres_fr/stop_a_l_anxiete.qmd
        - content/livres_fr/sur_le_fil_du_rasoir.qmd
        - content/livres_fr/surmonter_l_alcoolisme.qmd
        - content/livres_fr/surmonter_la_depression_1.qmd
        - content/livres_fr/surmonter_la_depression_2.qmd
        - content/livres_fr/tabagisme_plaisir_dependance.qmd
        - content/livres_fr/vaincre_l_anxiete_sans_medoc.qmd
        - content/livres_fr/vieillissement_bipolaire_schizo.qmd
        
    - id: books_other
      title: "Books (other)"
      #collapse-level: 2
      contents:
        - content/books_other/index.qmd
        - content/books_other/defeat_insomnia.qmd
        - content/books_other/invinga_dependenta_de_alcool.qmd
        - content/books_other/nespavost_zbavte_se_ji_navzdy.qmd
        - content/books_other/sleep_better.qmd
        - content/books_other/strategies_fast_recovery.qmd
        - content/books_other/words_of_pain.qmd
        - content/books_other/لا للقلق.qmd

    - id: publications_communications
      title: "Publications & communications"
      #collapse-level: 2
      contents:
        - content/publications_communications/index.qmd
        - content/publications_communications/chapitres_ouvrages.qmd
        - content/publications_communications/articles_revues_indexees.qmd
        - content/publications_communications/articles_revues_non_indexees_avec_comite.qmd
        - content/publications_communications/articles_revues_non_indexees_sans_comite.qmd
        - content/publications_communications/communications_congres_internationaux.qmd
        - content/publications_communications/communications_congres_nationaux.qmd
        - content/publications_communications/posters_congres.qmd
        - content/publications_communications/interviews.qmd

    - id: autres_activites
      title: "Autres activités"
      #collapse-level: 2
      contents:
        - content/autres_activites/index.qmd
        - content/autres_activites/encadrement_recherche.qmd
        - content/autres_activites/autre.qmd

filters:
  - lightbox
  - black-formatter

lightbox: auto

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    code-overflow: wrap
    template-partials: 
      - ../../_partials/title-block-link-buttons/title-block.html


crossref:
  chapters: true

format-links: false
author: Jérôme Palazzolo
page-layout: article
title-block-banner: "#e9f3fa"

validate-yaml: false
jupyter: python3

wrap: preserve
keep-ipynb: false
#cache: true

#bibliography: references.bib

citation:
  title: "Site du Dr Jérôme Palazzolo"
  type: book
  language: fr
  url: https://www.docteurjeromepalazzolo.fr  # A modifier ?

appendix-cite-as: display
google-scholar: true
commentable: true
