project:
  type: website
  render:

    - index.qmd

    # - content/le_docteur/index.qmd
    - content/le_docteur/consultations.qmd
    - content/le_docteur/biographie.qmd
    - content/le_docteur/cv.qmd

    - content/livres/index.qmd
    - content/livres/3_approches_du_soin_psychique.qmd
    - content/livres/apprendre_a_gerer_son_stress.qmd
    - content/livres/au_dela_des_mots.qmd
    - content/livres/cannabis_du_plaisir_au_risque.qmd
    - content/livres/cas_cliniques_en_tcc_1.qmd
    - content/livres/cas_cliniques_en_tcc_2.qmd
    - content/livres/cas_cliniques_en_tcc_3.qmd
    - content/livres/chambre_isolement_contention.qmd
    - content/livres/coachez_votre_vie.qmd
    - content/livres/communication_observance_psy.qmd
    - content/livres/controle_et_gestion_du_stress.qmd
    - content/livres/depression_et_anxiete.qmd
    - content/livres/dire_pour_vivre.qmd
    - content/livres/dynamique_equipe_soignante.qmd
    - content/livres/ecarts_de_conduite.qmd
    - content/livres/en_finir_avec_l_insomnie.qmd
    - content/livres/epreuve_maladie_organique.qmd
    - content/livres/gerer_les_conflits.qmd
    - content/livres/gestion_stress_aquaphobie_tcc.qmd
    - content/livres/guerir_vite.qmd
    - content/livres/guide_urgence_psychiatrique.qmd
    - content/livres/homosexualite_en_afrique.qmd
    - content/livres/information_du_patient.qmd
    - content/livres/informer_patient_en_psychiatrie.qmd
    - content/livres/institution_psychiatrique.qmd
    - content/livres/isolement_contention_contrainte.qmd
    - content/livres/je_me_libere_de_mes_phobies.qmd
    - content/livres/je_triomphe_de_l_insomnie.qmd
    - content/livres/la_psychologie_positive.qmd
    - content/livres/le_cannabis_en_question.qmd
    - content/livres/les_essentiels_des_tcc.qmd
    - content/livres/les_exclus_de_la_cite.qmd
    - content/livres/les_psychoses.qmd
    - content/livres/les_tcc_1.qmd
    - content/livres/les_tcc_2.qmd
    - content/livres/les_tcc_du_sujet_age.qmd
    - content/livres/les_tcc_manuel_pratique.qmd
    - content/livres/les_therapies_breves.qmd
    - content/livres/les_troubles_de_la_personnalite.qmd
    - content/livres/ma_bible_des_tcc.qmd
    - content/livres/mots_corps_maux_ame.qmd
    - content/livres/observance_medicamenteuse.qmd
    - content/livres/petit_precis_psychologie_positive.qmd
    - content/livres/petite_histoire_masturbation.qmd
    - content/livres/psychotherapies_du_sujet_age.qmd
    - content/livres/reflexions_vieillissement.qmd
    - content/livres/risques_et_plongee.qmd
    - content/livres/sante_mentale_neurologique.qmd
    - content/livres/schizophrenie_diagnostic.qmd
    - content/livres/se_soigner_par_les_tcc.qmd
    - content/livres/sida_et_seropositivite.qmd
    - content/livres/sortir_toxicomanie_addictions.qmd
    - content/livres/stop_a_l_anxiete_sans_medoc.qmd
    - content/livres/stop_a_l_anxiete.qmd
    - content/livres/sur_le_fil_du_rasoir.qmd
    - content/livres/surmonter_l_alcoolisme.qmd
    - content/livres/surmonter_la_depression_1.qmd
    - content/livres/surmonter_la_depression_2.qmd
    - content/livres/tabagisme_plaisir_dependance.qmd
    - content/livres/vaincre_l_anxiete_sans_medoc.qmd
    - content/livres/vieillissement_bipolaire_schizo.qmd

    - content/livres/defeat_insomnia.qmd
    - content/livres/invinga_dependenta_de_alcool.qmd
    - content/livres/nespavost_zbavte_se_ji_navzdy.qmd
    - content/livres/sleep_better.qmd
    - content/livres/strategies_fast_recovery.qmd
    - content/livres/words_of_pain.qmd
    - content/livres/لا للقلق.qmd

    # - content/publications_communications/index.qmd
    - content/publications_communications/chapitres_ouvrages.qmd
    - content/publications_communications/articles_revues_indexees.qmd
    - content/publications_communications/articles_revues_non_indexees_avec_comite.qmd
    - content/publications_communications/articles_revues_non_indexees_sans_comite.qmd
    - content/publications_communications/communications_congres_internationaux.qmd
    - content/publications_communications/communications_congres_nationaux.qmd
    - content/publications_communications/posters_congres.qmd
    - content/publications_communications/interviews.qmd

    # - content/autres_activites/index.qmd
    - content/autres_activites/encadrement_recherche.qmd
    # - content/autres_activites/autre.qmd

website:
  title: "Dr Jérôme Palazzolo"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: img/logo.jpeg
  cookie-consent:
    type: express
  google-analytics: "G-JWQSW5E8BY"
  navbar:
    background: "white"
    search: true
    left:
      - file: index.qmd
        text: Accueil
      - sidebar:le_docteur
      - href: https://www.facebook.com/media/set/?set=a.10150356662827691&type=3
        text: Interviews
      # - sidebar:livres
      - file: content/livres/index.qmd
        text: Livres
      - href: https://www.youtube.com/channel/UCMF4Vhgt6gOYQaiE2jlKoHw
        text: Vidéos
      - sidebar:publications_communications
      # - sidebar:autres_activites
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jerome-palazzolo/
      - icon: facebook
        href: https://www.facebook.com/DrPalazzolo/
      - icon: instagram
        href: https://www.instagram.com/palazz06/
      - icon: meta
        href: https://www.threads.net/@palazz06
      - icon: youtube
        href: https://www.youtube.com/channel/UCMF4Vhgt6gOYQaiE2jlKoHw
      - icon: twitter
        href: https://twitter.com/palazz06
      - icon: github
        menu:
          - text: Code source
            url:  https://github.com/antoine-palazz/site-dr-palazzolo
  # comments:
  #  giscus:
  #    repo: antoine-palazz/site-dr-palazzolo
  twitter-card: true
  site-url: https://docteurjeromepalazzolo.fr
  repo-url: https://github.com/antoine-palazz/site-dr-palazzolo
  repo-branch: main
  issue-url: https://github.com/antoine-palazz/site-dr-palazzolo/issues/new
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Site du Dr Jérôme Palazzolo<br>
      Licence MIT<br>
      Code source disponible sur [`Github`](https://github.com/antoine-palazz/site-dr-palazzolo)
    right: |
      Site construit avec [`Quarto`](https://quarto.org/)<br>
      Par [Antoine Palazzolo](https://www.linkedin.com/in/antoine-palazzolo/)<br>

  sidebar: 

    - id: home
      title: "Accueil"
      href: index.qmd

    - id: le_docteur
      title: "Le docteur"
      #collapse-level: 2
      contents:
        # - content/le_docteur/index.qmd
        - content/le_docteur/consultations.qmd
        - content/le_docteur/biographie.qmd
        - content/le_docteur/cv.qmd

    - id: livres
      title: "Livres"
      #collapse-level: 2
      contents:
        - content/livres/index.qmd
        - content/livres/3_approches_du_soin_psychique.qmd
        - content/livres/apprendre_a_gerer_son_stress.qmd
        - content/livres/au_dela_des_mots.qmd
        - content/livres/cannabis_du_plaisir_au_risque.qmd
        - content/livres/cas_cliniques_en_tcc_1.qmd
        - content/livres/cas_cliniques_en_tcc_2.qmd
        - content/livres/cas_cliniques_en_tcc_3.qmd
        - content/livres/chambre_isolement_contention.qmd
        - content/livres/coachez_votre_vie.qmd
        - content/livres/communication_observance_psy.qmd
        - content/livres/controle_et_gestion_du_stress.qmd
        - content/livres/depression_et_anxiete.qmd
        - content/livres/dire_pour_vivre.qmd
        - content/livres/dynamique_equipe_soignante.qmd
        - content/livres/ecarts_de_conduite.qmd
        - content/livres/en_finir_avec_l_insomnie.qmd
        - content/livres/epreuve_maladie_organique.qmd
        - content/livres/gerer_les_conflits.qmd
        - content/livres/gestion_stress_aquaphobie_tcc.qmd
        - content/livres/guerir_vite.qmd
        - content/livres/guide_urgence_psychiatrique.qmd
        - content/livres/homosexualite_en_afrique.qmd
        - content/livres/information_du_patient.qmd
        - content/livres/informer_patient_en_psychiatrie.qmd
        - content/livres/institution_psychiatrique.qmd
        - content/livres/isolement_contention_contrainte.qmd
        - content/livres/je_me_libere_de_mes_phobies.qmd
        - content/livres/je_triomphe_de_l_insomnie.qmd
        - content/livres/la_psychologie_positive.qmd
        - content/livres/le_cannabis_en_question.qmd
        - content/livres/les_essentiels_des_tcc.qmd
        - content/livres/les_exclus_de_la_cite.qmd
        - content/livres/les_psychoses.qmd
        - content/livres/les_tcc_1.qmd
        - content/livres/les_tcc_2.qmd
        - content/livres/les_tcc_du_sujet_age.qmd
        - content/livres/les_tcc_manuel_pratique.qmd
        - content/livres/les_therapies_breves.qmd
        - content/livres/les_troubles_de_la_personnalite.qmd
        - content/livres/ma_bible_des_tcc.qmd
        - content/livres/mots_corps_maux_ame.qmd
        - content/livres/observance_medicamenteuse.qmd
        - content/livres/petit_precis_psychologie_positive.qmd
        - content/livres/petite_histoire_masturbation.qmd
        - content/livres/psychotherapies_du_sujet_age.qmd
        - content/livres/reflexions_vieillissement.qmd
        - content/livres/risques_et_plongee.qmd
        - content/livres/sante_mentale_neurologique.qmd
        - content/livres/schizophrenie_diagnostic.qmd
        - content/livres/se_soigner_par_les_tcc.qmd
        - content/livres/sida_et_seropositivite.qmd
        - content/livres/sortir_toxicomanie_addictions.qmd
        - content/livres/stop_a_l_anxiete_sans_medoc.qmd
        - content/livres/stop_a_l_anxiete.qmd
        - content/livres/sur_le_fil_du_rasoir.qmd
        - content/livres/surmonter_l_alcoolisme.qmd
        - content/livres/surmonter_la_depression_1.qmd
        - content/livres/surmonter_la_depression_2.qmd
        - content/livres/tabagisme_plaisir_dependance.qmd
        - content/livres/vaincre_l_anxiete_sans_medoc.qmd
        - content/livres/vieillissement_bipolaire_schizo.qmd
        - content/livres/defeat_insomnia.qmd
        - content/livres/invinga_dependenta_de_alcool.qmd
        - content/livres/nespavost_zbavte_se_ji_navzdy.qmd
        - content/livres/sleep_better.qmd
        - content/livres/strategies_fast_recovery.qmd
        - content/livres/words_of_pain.qmd
        - content/livres/لا للقلق.qmd

    - id: publications_communications
      title: "Travaux"
      #collapse-level: 2
      contents:
        # - content/publications_communications/index.qmd
        - content/publications_communications/chapitres_ouvrages.qmd
        - content/publications_communications/articles_revues_indexees.qmd
        - content/publications_communications/articles_revues_non_indexees_avec_comite.qmd
        - content/publications_communications/articles_revues_non_indexees_sans_comite.qmd
        - content/publications_communications/communications_congres_internationaux.qmd
        - content/publications_communications/communications_congres_nationaux.qmd
        - content/publications_communications/posters_congres.qmd
        - content/publications_communications/interviews.qmd

    - id: autres_activites
      title: "Autres"
      #collapse-level: 2
      contents:
        # - content/autres_activites/index.qmd
        - content/autres_activites/encadrement_recherche.qmd
        # - content/autres_activites/autre.qmd

filters:
  - lightbox
  - black-formatter

lightbox: auto

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    code-overflow: wrap
    template-partials: 
      - _partials/title-block-link-buttons/title-block.html


crossref:
  chapters: true

format-links: false
author: Jérôme Palazzolo
page-layout: article
title-block-banner: "#e9f3fa"

validate-yaml: false
jupyter: python3

wrap: preserve
keep-ipynb: false
#cache: true

#bibliography: references.bib

citation:
  title: "Site du Dr Jérôme Palazzolo"
  type: book
  language: fr
  url: https://www.docteurjeromepalazzolo.fr

appendix-cite-as: display
google-scholar: true
commentable: false
